language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -qq flake8
  - pip install codecov
  - python setup.py install

script:
  - coverage run setup.py pytest
  - flake8 --version
  - flake8 pyBLS

after_success:
  - codecov --token='24ace9df-2109-4d06-9551-32d62f89ff78'